
name: SSH Session

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
      - name: Keep runner alive
        run: |
          echo "Keeping session alive..."
          sleep 21600
